version: "3.9"
services:
  asterisk:
    build: ./asterisk
    ports:
      - "5060:5060/udp"
      - "10000-20000:10000-20000/udp"
      - "8088:8088/tcp"
    volumes:
      - ./asterisk/configs:/etc/asterisk
  node-app:
    build: ./node-app
    depends_on: [asterisk]
    environment:
      - ARI_URL=http://asterisk:8088
      - ARI_USER=asterisk
      - ARI_PASS=asterisk
      - APP_NAME=hello-app
    network_mode: service:asterisk
