name: Build & Push Asterisk Image

on:
  workflow_dispatch:  # You trigger this manually

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      - name: Build and push Asterisk image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/asterisk-ari:22.3.0 ./asterisk
          docker push ${{ secrets.DOCKER_HUB_USER }}/asterisk-ari:22.3.0
